[files]
extend-exclude = [
  ".git/",
  ".pixi/",
  "**/*.snap",
  "**/*.txt",
  "crates/rattler_libsolv_c",
  "test-data",
  "crates/rattler_index/tests/test_index.rs"
]
ignore-hidden = false

[default.extend-words]
strat = "strat"
haa = "haa"
